# 🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



```array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])```

In [2]:
import numpy as np

array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list ```[3.14, 2.17, 0, 1, 2]``` into a NumPy array and convert its data type to integer.

Expected Output:



``array([3, 2, 0, 1, 2])``

In [3]:
list_2 = [3.14, 2.17, 0, 1, 2]
array_2 = np.array(list_2, dtype=int)
array_2

array([3, 2, 0, 1, 2])

# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



``` 
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
```

In [4]:
array_3 = np.arange(1, 10).reshape(3, 3)
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:


```
array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])
```

In [6]:
array_4 = np.random.rand(4, 5)
array_4

array([[0.01990945, 0.88398703, 0.88168386, 0.1798295 , 0.79839624],
       [0.42132272, 0.1340767 , 0.89262222, 0.81391834, 0.25397286],
       [0.23141105, 0.41080269, 0.55299086, 0.49496376, 0.47780618],
       [0.61495034, 0.67549841, 0.60735574, 0.30104703, 0.91294299]])

# 🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:


```
array([20, 21, 22, 23, 24])
```

In [7]:
array_5 = np.array([[10, 11, 12, 13, 14], 
                    [20, 21, 22, 23, 24], 
                    [30, 31, 32, 33, 34]])
row_2 = array_5[1]
row_2

array([20, 21, 22, 23, 24])

# 🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



```array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])```

In [9]:
array_6 = np.arange(10)[::-1]
array_6

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# 🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:


```
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
       

In [11]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



```Sum: 45, Average: 4.5```

In [12]:
array_8 = np.arange(10)
sum_8 = np.sum(array_8)
average_8 = np.mean(array_8)

print(f'Sum: {sum_8}, Average: {average_8}')

Sum: 45, Average: 4.5


# 🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:


```
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
array_9 = np.arange(1, 21).reshape(4, 5)
array_9

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# 🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



```array([1, 3, 5, 7, 9])```

In [14]:
array_10 = np.arange(10)
odd_numbers = array_10[array_10 % 2 == 1]
odd_numbers

array([1, 3, 5, 7, 9])